// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package main

import "encoding/json"
import "fmt"
import "reflect"
import "regexp"
import "time"

type EcosystemName string

const EcosystemNameAlmaLinux EcosystemName = "AlmaLinux"
const EcosystemNameAlpaquita EcosystemName = "Alpaquita"
const EcosystemNameAlpine EcosystemName = "Alpine"
const EcosystemNameAndroid EcosystemName = "Android"
const EcosystemNameBellSoftHardenedContainers EcosystemName = "BellSoft Hardened Containers"
const EcosystemNameBioconductor EcosystemName = "Bioconductor"
const EcosystemNameBitnami EcosystemName = "Bitnami"
const EcosystemNameCRAN EcosystemName = "CRAN"
const EcosystemNameChainguard EcosystemName = "Chainguard"
const EcosystemNameConanCenter EcosystemName = "ConanCenter"
const EcosystemNameCratesIo EcosystemName = "crates.io"
const EcosystemNameDebian EcosystemName = "Debian"
const EcosystemNameGHC EcosystemName = "GHC"
const EcosystemNameGitHubActions EcosystemName = "GitHub Actions"
const EcosystemNameGo EcosystemName = "Go"
const EcosystemNameHackage EcosystemName = "Hackage"
const EcosystemNameHex EcosystemName = "Hex"
const EcosystemNameKubernetes EcosystemName = "Kubernetes"
const EcosystemNameLinux EcosystemName = "Linux"
const EcosystemNameMageia EcosystemName = "Mageia"
const EcosystemNameMaven EcosystemName = "Maven"
const EcosystemNameMinimOS EcosystemName = "MinimOS"
const EcosystemNameNpm EcosystemName = "npm"
const EcosystemNameNuGet EcosystemName = "NuGet"
const EcosystemNameOSSFuzz EcosystemName = "OSS-Fuzz"
const EcosystemNameOpenEuler EcosystemName = "openEuler"
const EcosystemNameOpenSUSE EcosystemName = "openSUSE"
const EcosystemNamePackagist EcosystemName = "Packagist"
const EcosystemNamePhotonOS EcosystemName = "Photon OS"
const EcosystemNamePub EcosystemName = "Pub"
const EcosystemNamePyPI EcosystemName = "PyPI"
const EcosystemNameRedHat EcosystemName = "Red Hat"
const EcosystemNameRockyLinux EcosystemName = "Rocky Linux"
const EcosystemNameRubyGems EcosystemName = "RubyGems"
const EcosystemNameSUSE EcosystemName = "SUSE"
const EcosystemNameSwiftURL EcosystemName = "SwiftURL"
const EcosystemNameUbuntu EcosystemName = "Ubuntu"
const EcosystemNameWolfi EcosystemName = "Wolfi"

var enumValues_EcosystemName = []interface{}{
	"AlmaLinux",
	"Alpaquita",
	"Alpine",
	"Android",
	"BellSoft Hardened Containers",
	"Bioconductor",
	"Bitnami",
	"Chainguard",
	"ConanCenter",
	"CRAN",
	"crates.io",
	"Debian",
	"GHC",
	"GitHub Actions",
	"Go",
	"Hackage",
	"Hex",
	"Kubernetes",
	"Linux",
	"Mageia",
	"Maven",
	"MinimOS",
	"npm",
	"NuGet",
	"openEuler",
	"openSUSE",
	"OSS-Fuzz",
	"Packagist",
	"Photon OS",
	"Pub",
	"PyPI",
	"Red Hat",
	"Rocky Linux",
	"RubyGems",
	"SUSE",
	"SwiftURL",
	"Ubuntu",
	"Wolfi",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *EcosystemName) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_EcosystemName {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_EcosystemName, v)
	}
	*j = EcosystemName(v)
	return nil
}

type EcosystemSuffix string

// UnmarshalJSON implements json.Unmarshaler.
func (j *EcosystemSuffix) UnmarshalJSON(value []byte) error {
	type Plain EcosystemSuffix
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if matched, _ := regexp.MatchString(`:.+`, string(plain)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "", `:.+`)
	}
	*j = EcosystemSuffix(plain)
	return nil
}

// These ecosystems are also documented at
// https://ossf.github.io/osv-schema/#affectedpackage-field
type EcosystemWithSuffix string

// UnmarshalJSON implements json.Unmarshaler.
func (j *EcosystemWithSuffix) UnmarshalJSON(value []byte) error {
	type Plain EcosystemWithSuffix
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if matched, _ := regexp.MatchString(`^(AlmaLinux|Alpaquita|Alpine|Android|BellSoft Hardened Containers|Bioconductor|Bitnami|Chainguard|ConanCenter|CRAN|crates\.io|Debian|GHC|GitHub Actions|Go|Hackage|Hex|Kubernetes|Linux|Mageia|Maven|MinimOS|npm|NuGet|openEuler|openSUSE|OSS-Fuzz|Packagist|Photon OS|Pub|PyPI|Red Hat|Rocky Linux|RubyGems|SUSE|SwiftURL|Ubuntu|Wolfi|GIT)(:.+)?$`, string(plain)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "", `^(AlmaLinux|Alpaquita|Alpine|Android|BellSoft Hardened Containers|Bioconductor|Bitnami|Chainguard|ConanCenter|CRAN|crates\.io|Debian|GHC|GitHub Actions|Go|Hackage|Hex|Kubernetes|Linux|Mageia|Maven|MinimOS|npm|NuGet|openEuler|openSUSE|OSS-Fuzz|Packagist|Photon OS|Pub|PyPI|Red Hat|Rocky Linux|RubyGems|SUSE|SwiftURL|Ubuntu|Wolfi|GIT)(:.+)?$`)
	}
	*j = EcosystemWithSuffix(plain)
	return nil
}

// These home databases are also documented at
// https://ossf.github.io/osv-schema/#id-modified-fields
type Prefix string

// UnmarshalJSON implements json.Unmarshaler.
func (j *Prefix) UnmarshalJSON(value []byte) error {
	type Plain Prefix
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if matched, _ := regexp.MatchString(`^(ASB-A|PUB-A|ALSA|ALBA|ALEA|BIT|CGA|CURL|CVE|DSA|DLA|ELA|DTSA|GHSA|GO|GSD|HSEC|KUBE|LBSEC|LSN|MAL|MINI|MGASA|OESA|OSV|openSUSE-SU|PHSA|PSF|PYSEC|RHBA|RHEA|RHSA|RLSA|RXSA|RSEC|RUSTSEC|SUSE-[SRFO]U|UBUNTU|USN|V8)-`, string(plain)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "", `^(ASB-A|PUB-A|ALSA|ALBA|ALEA|BIT|CGA|CURL|CVE|DSA|DLA|ELA|DTSA|GHSA|GO|GSD|HSEC|KUBE|LBSEC|LSN|MAL|MINI|MGASA|OESA|OSV|openSUSE-SU|PHSA|PSF|PYSEC|RHBA|RHEA|RHSA|RLSA|RXSA|RSEC|RUSTSEC|SUSE-[SRFO]U|UBUNTU|USN|V8)-`)
	}
	*j = Prefix(plain)
	return nil
}

// A schema for describing a vulnerability in an open source package. See also
// https://ossf.github.io/osv-schema/
type SchemaJson interface{}

type SchemaJsonAffectedElem struct {
	// DatabaseSpecific corresponds to the JSON schema field "database_specific".
	DatabaseSpecific map[string]interface{} `json:"database_specific,omitempty" yaml:"database_specific,omitempty" mapstructure:"database_specific,omitempty"`

	// EcosystemSpecific corresponds to the JSON schema field "ecosystem_specific".
	EcosystemSpecific map[string]interface{} `json:"ecosystem_specific,omitempty" yaml:"ecosystem_specific,omitempty" mapstructure:"ecosystem_specific,omitempty"`

	// Package corresponds to the JSON schema field "package".
	Package *SchemaJsonAffectedElemPackage `json:"package,omitempty" yaml:"package,omitempty" mapstructure:"package,omitempty"`

	// Ranges corresponds to the JSON schema field "ranges".
	Ranges []interface{} `json:"ranges,omitempty" yaml:"ranges,omitempty" mapstructure:"ranges,omitempty"`

	// Severity corresponds to the JSON schema field "severity".
	Severity Severity `json:"severity,omitempty" yaml:"severity,omitempty" mapstructure:"severity,omitempty"`

	// Versions corresponds to the JSON schema field "versions".
	Versions []string `json:"versions,omitempty" yaml:"versions,omitempty" mapstructure:"versions,omitempty"`
}

type SchemaJsonAffectedElemPackage struct {
	// Ecosystem corresponds to the JSON schema field "ecosystem".
	Ecosystem EcosystemWithSuffix `json:"ecosystem" yaml:"ecosystem" mapstructure:"ecosystem"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// Purl corresponds to the JSON schema field "purl".
	Purl *string `json:"purl,omitempty" yaml:"purl,omitempty" mapstructure:"purl,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SchemaJsonAffectedElemPackage) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["ecosystem"]; raw != nil && !ok {
		return fmt.Errorf("field ecosystem in SchemaJsonAffectedElemPackage: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in SchemaJsonAffectedElemPackage: required")
	}
	type Plain SchemaJsonAffectedElemPackage
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = SchemaJsonAffectedElemPackage(plain)
	return nil
}

type SchemaJsonCreditsElem struct {
	// Contact corresponds to the JSON schema field "contact".
	Contact []string `json:"contact,omitempty" yaml:"contact,omitempty" mapstructure:"contact,omitempty"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// Type corresponds to the JSON schema field "type".
	Type *SchemaJsonCreditsElemType `json:"type,omitempty" yaml:"type,omitempty" mapstructure:"type,omitempty"`
}

type SchemaJsonCreditsElemType string

const SchemaJsonCreditsElemTypeANALYST SchemaJsonCreditsElemType = "ANALYST"
const SchemaJsonCreditsElemTypeCOORDINATOR SchemaJsonCreditsElemType = "COORDINATOR"
const SchemaJsonCreditsElemTypeFINDER SchemaJsonCreditsElemType = "FINDER"
const SchemaJsonCreditsElemTypeOTHER SchemaJsonCreditsElemType = "OTHER"
const SchemaJsonCreditsElemTypeREMEDIATIONDEVELOPER SchemaJsonCreditsElemType = "REMEDIATION_DEVELOPER"
const SchemaJsonCreditsElemTypeREMEDIATIONREVIEWER SchemaJsonCreditsElemType = "REMEDIATION_REVIEWER"
const SchemaJsonCreditsElemTypeREMEDIATIONVERIFIER SchemaJsonCreditsElemType = "REMEDIATION_VERIFIER"
const SchemaJsonCreditsElemTypeREPORTER SchemaJsonCreditsElemType = "REPORTER"
const SchemaJsonCreditsElemTypeSPONSOR SchemaJsonCreditsElemType = "SPONSOR"
const SchemaJsonCreditsElemTypeTOOL SchemaJsonCreditsElemType = "TOOL"

var enumValues_SchemaJsonCreditsElemType = []interface{}{
	"FINDER",
	"REPORTER",
	"ANALYST",
	"COORDINATOR",
	"REMEDIATION_DEVELOPER",
	"REMEDIATION_REVIEWER",
	"REMEDIATION_VERIFIER",
	"TOOL",
	"SPONSOR",
	"OTHER",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SchemaJsonCreditsElemType) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_SchemaJsonCreditsElemType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_SchemaJsonCreditsElemType, v)
	}
	*j = SchemaJsonCreditsElemType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SchemaJsonCreditsElem) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in SchemaJsonCreditsElem: required")
	}
	type Plain SchemaJsonCreditsElem
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = SchemaJsonCreditsElem(plain)
	return nil
}

type SchemaJsonReferencesElem struct {
	// Type corresponds to the JSON schema field "type".
	Type SchemaJsonReferencesElemType `json:"type" yaml:"type" mapstructure:"type"`

	// Url corresponds to the JSON schema field "url".
	Url string `json:"url" yaml:"url" mapstructure:"url"`
}

type SchemaJsonReferencesElemType string

const SchemaJsonReferencesElemTypeADVISORY SchemaJsonReferencesElemType = "ADVISORY"
const SchemaJsonReferencesElemTypeARTICLE SchemaJsonReferencesElemType = "ARTICLE"
const SchemaJsonReferencesElemTypeDETECTION SchemaJsonReferencesElemType = "DETECTION"
const SchemaJsonReferencesElemTypeDISCUSSION SchemaJsonReferencesElemType = "DISCUSSION"
const SchemaJsonReferencesElemTypeEVIDENCE SchemaJsonReferencesElemType = "EVIDENCE"
const SchemaJsonReferencesElemTypeFIX SchemaJsonReferencesElemType = "FIX"
const SchemaJsonReferencesElemTypeGIT SchemaJsonReferencesElemType = "GIT"
const SchemaJsonReferencesElemTypeINTRODUCED SchemaJsonReferencesElemType = "INTRODUCED"
const SchemaJsonReferencesElemTypePACKAGE SchemaJsonReferencesElemType = "PACKAGE"
const SchemaJsonReferencesElemTypeREPORT SchemaJsonReferencesElemType = "REPORT"
const SchemaJsonReferencesElemTypeWEB SchemaJsonReferencesElemType = "WEB"

var enumValues_SchemaJsonReferencesElemType = []interface{}{
	"ADVISORY",
	"ARTICLE",
	"DETECTION",
	"DISCUSSION",
	"REPORT",
	"FIX",
	"INTRODUCED",
	"GIT",
	"PACKAGE",
	"EVIDENCE",
	"WEB",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SchemaJsonReferencesElemType) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_SchemaJsonReferencesElemType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_SchemaJsonReferencesElemType, v)
	}
	*j = SchemaJsonReferencesElemType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SchemaJsonReferencesElem) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in SchemaJsonReferencesElem: required")
	}
	if _, ok := raw["url"]; raw != nil && !ok {
		return fmt.Errorf("field url in SchemaJsonReferencesElem: required")
	}
	type Plain SchemaJsonReferencesElem
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = SchemaJsonReferencesElem(plain)
	return nil
}

type Severity []interface{}

type SeverityElemType string

const SeverityElemTypeCVSSV2 SeverityElemType = "CVSS_V2"
const SeverityElemTypeCVSSV3 SeverityElemType = "CVSS_V3"
const SeverityElemTypeCVSSV4 SeverityElemType = "CVSS_V4"
const SeverityElemTypeUbuntu SeverityElemType = "Ubuntu"

var enumValues_SeverityElemType = []interface{}{
	"CVSS_V2",
	"CVSS_V3",
	"CVSS_V4",
	"Ubuntu",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SeverityElemType) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_SeverityElemType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_SeverityElemType, v)
	}
	*j = SeverityElemType(v)
	return nil
}

type Timestamp time.Time
